/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 05-abr.-2023 8:09:17 p.�m. 				*/
/*  DBMS       : Oracle 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

begin
	EXECUTE IMMEDIATE 'DROP TABLE   USUARIO CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

/* Create Tables */

CREATE TABLE  USUARIO
(
	CODIGO NUMBER(10) NOT NULL,
	NOMBRE VARCHAR2(50) NOT NULL,
	APELLIDO VARCHAR2(50) NOT NULL,
	EMAIL VARCHAR2(50) NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks, Triggers */

ALTER TABLE  USUARIO 
 ADD CONSTRAINT PK_USUARIO
	PRIMARY KEY (CODIGO) 
 USING INDEX
;

ALTER TABLE  USUARIO 
 ADD CONSTRAINT UK_USUARIO_EMAIL UNIQUE (EMAIL) 
 USING INDEX
;
